---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits
Our project will be done using a sequence of save and commits.

## First Verse 
'Twas brillig, and the slithy toves  
did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
"Beware the Jabberwock, my son!  
The jaws that bite, the claws that catch!  
Beware the Jubjub bird, and shun  
The frumious Bandersnatch!"

## Second Verse
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  
  
Then took the other, as just as fair,  
And having perhaps the better claim,  
Because it was grassy and wanted wear;  
Though as for that the passing there  
Had worn them really about the same,  


## Third Verse
The sun was shining on the sea,  
Shining with all his might;  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  
The middle of the night.  
  
The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done--  
"it's very rude of him," she said,  
"To come and spoil the fun!"  




## Last Verse
I come before you, to stand behind you,  
To tell you something I know nothing about.  
Admission is free, so pay at the door;  
Pull up a chair and sit on the floor:  
  
One dark day in the middle of the night,  
Two dead boys woke up to fight.  
Back to back they faced each other,  
Drew their swords and shot eachother.  


